---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/11/6 17:34
---
local voucherId = ARGV[1]

local stockKey = 'seckillVoucher:' .. voucherId
redis.call('set',stockKey,ARGV[2])
