---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/11/5 22:44
---

local voucherId = ARGV[1]
local userId = ARGV[2]
--local stockKey = 'seckillVoucher:' .. voucherId

local stockKey = 'seckillVoucher:' .. voucherId

local orderKey = 'seckillUser:' .. voucherId

redis.call('set','tt',1)
 --  local stock =  redis.call('get',stockKey)
    --库存不足返回1
if (tonumber(redis.call('get', stockKey)) <= 0) then
    return 1
end
    --用户存在返回2
if (redis.call('sismember', orderKey,userId) == 1) then
    return 2
end
    --扣减库存
redis.call('incrby',stockKey,-1)
    --将userId存入sadd集合
redis.call('sadd', orderKey,userId)
return 0

