---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/11/5 16:26
---

local threadId = ARGV[1]
local key = redis.call(get,KEYS[1])
if(threadId == key) then
    return redis.call(del,KEYS[1])
end
return 0